version: '1.0.0'

services:

#UI http://localhost:15800/#/
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    container_name: RabbitMQ
    hostname: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=StasPI
      - RABBITMQ_DEFAULT_PASS=Password1
    ports:
      # AMQP protocol port
      - 5800:5672
      - 15800:15672
    volumes:
      - ./config/definitions.json:/opt/definitions.json:ro
      - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro