version: '1.0.0'

services:

#UI http://localhost:5050/browser/
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: StasPI@github.com
      PGADMIN_DEFAULT_PASSWORD: Password1
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./config/pgpassfile:/pgadmin4/pgpassfile # passwords for the connections in this file

#connection string "Host=localhost;Port=5432;Database=postgres;Username=sa;Password=Password1"
  postgres:
    restart: unless-stopped
    image: postgres
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Password1
      PGDATA: "/var/lib/postgresql/data/data"
    volumes:
      - .:/var/lib/postgresql/data

volumes:
 postgres:
 pgadmin: