version: '1.0.0'

services:

#connection string "Host=localhost;Port=1433;Username=sa;Password=Password1"
  mssql:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
    hostname: localhost
    ports:
      - 1433:1433
    volumes:
      - type: bind
        source: ./data
        target: /var/opt/mssql/data/
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1
      MSSQL_PID: Developer
      MSSQL_COLLATION: Cyrillic_General_CI_AS
      MSSQL_AGENT_ENABLED: false
      # MSSQL_MASTER_DATA_FILE:
      # MSSQL_MASTER_LOG_FILE: 